package poker;

import card.Card;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Abstract collection of cards.
 * 
 * @author Sebastian Björkqvist
 */
public abstract class AbstractCardCollection {

    private final Set<Card> cards;
    private final int maximumAmountOfCardsInCollection;    

    /**
     * Creates a new AbstractCardCollection
     * 
     * @param maximumAmountOfCardsInCollection 
     * @throws IllegalArgumentException if maximumAmountOfCardsInCollection isn't positive.
     */
    public AbstractCardCollection(int maximumAmountOfCardsInCollection) {
        if (maximumAmountOfCardsInCollection <= 0) {
            throw new IllegalArgumentException("Maximum amount of cards in collection must be positive");
        }
        this.cards = new HashSet<Card>();
        this.maximumAmountOfCardsInCollection = maximumAmountOfCardsInCollection;
    }

    /**
     * Adds a card to the collection.
     *
     * Doesn't add a card and returns false if the collection is full.
     *
     * @param card
     * @return true if card is added, false otherwise.
     * @throws IllegalArgumentException if the collection already contains the card
     */
    public boolean addCard(Card card) {
        if (card == null) {
            throw new IllegalArgumentException("Null card can't be added to hand");
        }
        if (cards.contains(card)) {
            throw new IllegalArgumentException("Hand already contains card " + card);
        }
        if (isFull()) {
            return false;
        }
        cards.add(card);
        return true;
    }

    /**
     * Returns the number of cards that the collection can hold.
     *
     * @return The number of cards the collection can hold
     */
    public int getMaximumAmountOfCardsInCollection() {
        return maximumAmountOfCardsInCollection;
    }

    /**
     * Tells if the collection is full.
     *
     * @return true if the collection is full, false otherwise.
     */
    public boolean isFull() {
        return cards.size() >= maximumAmountOfCardsInCollection;
    }
    
    /**
     * Returns the number of cards in the hand.
     *
     * @return The number of cards in the hand
     */
    public int getNumberOfCards() {
        return cards.size();
    }

    /**
     * Returns a copy of the list of cards that the collection contains.
     *
     * @return List of cards
     */
    public List<Card> getCards() {
        return new ArrayList<Card>(cards);
    }

    /**
     * HashCode for Abstract card collection.
     * 
     * Generated by NetBeans.
     * 
     * @return 
     */
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + (this.cards != null ? this.cards.hashCode() : 0);
        hash = 37 * hash + this.maximumAmountOfCardsInCollection;
        return hash;
    }

    /**
     * Equals method for AbstractCardCollection.
     * 
     * Generated by NetBeans.
     * 
     * @param obj
     * @return 
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AbstractCardCollection other = (AbstractCardCollection) obj;
        if (this.cards != other.cards && (this.cards == null || !this.cards.equals(other.cards))) {
            return false;
        }
        if (this.maximumAmountOfCardsInCollection != other.maximumAmountOfCardsInCollection) {
            return false;
        }
        return true;
    }
 
    @Override
    public String toString() {
        return cards.toString();
    }
}
